import './sass/main.scss';
import './js/header-library.js';
import './js/renderTrendingFilms.js';
import './js/back-to-top.js';
import './js/developers.js';
import './js/search-film.js';
import './js/renderModalFilmPage';
import './js/pagination.js';
import './js/newBtn.js';
